### ISSUE TITLE
How did you compile these?

### ISSUE THREAD

**Issue by XEN486** [andymcca/libretro-cores-leap#7]
I know this isn't really an issue but I want to compile my own cores but I don't really know how you cross-compiled it

**Comment by andymcca** [comment]
You need to follow the 'Do your own build' instructions on the Retroleap
github page to get the appropriate Toolchain and to build cores - at least,
that's how I did it.

**Comment by XEN486** [comment]
is it possible to add custom cores? I do not see the option to do that anywhere

**Comment by andymcca** [comment]
It's a hobbyist project so you really need to be familiar with Buildroot or
know what you're doing with building from source in general.  I didn't know
what the hell I was doing to begin with 😂 easiest is to select a core you
want to build using the Buildroot config and then substitute the files in
that folder with the custom core ones you want to build.  It can be a good
deal of messing about to get something built though.

**Comment by XEN486** [comment]
ah alright! thanks for the advice, I will try and if the build succeeds then I will close the issue

**Comment by XEN486** [comment]
got cores to build! thanks!!!
